package com.hand.pojo;

// Generated 2015-8-20 23:30:34 by Hibernate Tools 3.4.0.CR1

/**
 * CustomerList generated by hbm2java
 */
public class CustomerList implements java.io.Serializable {

	private CustomerListId id;

	public CustomerList() {
	}

	public CustomerList(CustomerListId id) {
		this.id = id;
	}

	public CustomerListId getId() {
		return this.id;
	}

	public void setId(CustomerListId id) {
		this.id = id;
	}

}
