package com.hand.pojo;

// Generated 2015-8-20 23:30:34 by Hibernate Tools 3.4.0.CR1

/**
 * DoTabl generated by hbm2java
 */
public class DoTabl implements java.io.Serializable {

	private DoTablId id;
	private Events events;
	private String dosomething;

	public DoTabl() {
	}

	public DoTabl(DoTablId id, Events events) {
		this.id = id;
		this.events = events;
	}

	public DoTabl(DoTablId id, Events events, String dosomething) {
		this.id = id;
		this.events = events;
		this.dosomething = dosomething;
	}

	public DoTablId getId() {
		return this.id;
	}

	public void setId(DoTablId id) {
		this.id = id;
	}

	public Events getEvents() {
		return this.events;
	}

	public void setEvents(Events events) {
		this.events = events;
	}

	public String getDosomething() {
		return this.dosomething;
	}

	public void setDosomething(String dosomething) {
		this.dosomething = dosomething;
	}

}
