package com.hand.pojo;

// Generated 2015-8-20 23:30:34 by Hibernate Tools 3.4.0.CR1

/**
 * DoTablId generated by hbm2java
 */
public class DoTablId implements java.io.Serializable {

	private int eventId;
	private int mapKey;

	public DoTablId() {
	}

	public DoTablId(int eventId, int mapKey) {
		this.eventId = eventId;
		this.mapKey = mapKey;
	}

	public int getEventId() {
		return this.eventId;
	}

	public void setEventId(int eventId) {
		this.eventId = eventId;
	}

	public int getMapKey() {
		return this.mapKey;
	}

	public void setMapKey(int mapKey) {
		this.mapKey = mapKey;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DoTablId))
			return false;
		DoTablId castOther = (DoTablId) other;

		return (this.getEventId() == castOther.getEventId())
				&& (this.getMapKey() == castOther.getMapKey());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEventId();
		result = 37 * result + this.getMapKey();
		return result;
	}

}
