package com.hand.pojo;

// Generated 2015-8-20 23:30:34 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Events generated by hbm2java
 */
public class Events implements java.io.Serializable {

	private Integer eventId;
	private Date eventDate;
	private String title;
	private String insetd;
	private Set doTabls = new HashSet(0);
	private Set foodTabs = new HashSet(0);
	private Set hobbyTabs = new HashSet(0);
	private Set phoneTabs = new HashSet(0);

	public Events() {
	}

	public Events(Date eventDate, String title, String insetd, Set doTabls,
			Set foodTabs, Set hobbyTabs, Set phoneTabs) {
		this.eventDate = eventDate;
		this.title = title;
		this.insetd = insetd;
		this.doTabls = doTabls;
		this.foodTabs = foodTabs;
		this.hobbyTabs = hobbyTabs;
		this.phoneTabs = phoneTabs;
	}

	public Integer getEventId() {
		return this.eventId;
	}

	public void setEventId(Integer eventId) {
		this.eventId = eventId;
	}

	public Date getEventDate() {
		return this.eventDate;
	}

	public void setEventDate(Date eventDate) {
		this.eventDate = eventDate;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getInsetd() {
		return this.insetd;
	}

	public void setInsetd(String insetd) {
		this.insetd = insetd;
	}

	public Set getDoTabls() {
		return this.doTabls;
	}

	public void setDoTabls(Set doTabls) {
		this.doTabls = doTabls;
	}

	public Set getFoodTabs() {
		return this.foodTabs;
	}

	public void setFoodTabs(Set foodTabs) {
		this.foodTabs = foodTabs;
	}

	public Set getHobbyTabs() {
		return this.hobbyTabs;
	}

	public void setHobbyTabs(Set hobbyTabs) {
		this.hobbyTabs = hobbyTabs;
	}

	public Set getPhoneTabs() {
		return this.phoneTabs;
	}

	public void setPhoneTabs(Set phoneTabs) {
		this.phoneTabs = phoneTabs;
	}

}
