package com.hand.pojo;

// Generated 2015-8-20 23:30:34 by Hibernate Tools 3.4.0.CR1

/**
 * FoodTab generated by hbm2java
 */
public class FoodTab implements java.io.Serializable {

	private String foodId;
	private Events events;
	private String food;

	public FoodTab() {
	}

	public FoodTab(String foodId, Events events) {
		this.foodId = foodId;
		this.events = events;
	}

	public FoodTab(String foodId, Events events, String food) {
		this.foodId = foodId;
		this.events = events;
		this.food = food;
	}

	public String getFoodId() {
		return this.foodId;
	}

	public void setFoodId(String foodId) {
		this.foodId = foodId;
	}

	public Events getEvents() {
		return this.events;
	}

	public void setEvents(Events events) {
		this.events = events;
	}

	public String getFood() {
		return this.food;
	}

	public void setFood(String food) {
		this.food = food;
	}

}
