package com.hand.pojo;

// Generated 2015-8-20 23:30:34 by Hibernate Tools 3.4.0.CR1

/**
 * HobbyTabId generated by hbm2java
 */
public class HobbyTabId implements java.io.Serializable {

	private int stuId;
	private String hobby;

	public HobbyTabId() {
	}

	public HobbyTabId(int stuId) {
		this.stuId = stuId;
	}

	public HobbyTabId(int stuId, String hobby) {
		this.stuId = stuId;
		this.hobby = hobby;
	}

	public int getStuId() {
		return this.stuId;
	}

	public void setStuId(int stuId) {
		this.stuId = stuId;
	}

	public String getHobby() {
		return this.hobby;
	}

	public void setHobby(String hobby) {
		this.hobby = hobby;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HobbyTabId))
			return false;
		HobbyTabId castOther = (HobbyTabId) other;

		return (this.getStuId() == castOther.getStuId())
				&& ((this.getHobby() == castOther.getHobby()) || (this
						.getHobby() != null && castOther.getHobby() != null && this
						.getHobby().equals(castOther.getHobby())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getStuId();
		result = 37 * result
				+ (getHobby() == null ? 0 : this.getHobby().hashCode());
		return result;
	}

}
