package com.hand.pojo;

// Generated 2015-8-20 23:30:34 by Hibernate Tools 3.4.0.CR1

/**
 * PhoneTabId generated by hbm2java
 */
public class PhoneTabId implements java.io.Serializable {

	private int eventId;
	private int position;

	public PhoneTabId() {
	}

	public PhoneTabId(int eventId, int position) {
		this.eventId = eventId;
		this.position = position;
	}

	public int getEventId() {
		return this.eventId;
	}

	public void setEventId(int eventId) {
		this.eventId = eventId;
	}

	public int getPosition() {
		return this.position;
	}

	public void setPosition(int position) {
		this.position = position;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PhoneTabId))
			return false;
		PhoneTabId castOther = (PhoneTabId) other;

		return (this.getEventId() == castOther.getEventId())
				&& (this.getPosition() == castOther.getPosition());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEventId();
		result = 37 * result + this.getPosition();
		return result;
	}

}
