package com.hand.pojo;

// Generated 2015-8-20 23:30:34 by Hibernate Tools 3.4.0.CR1

/**
 * PhoneTab generated by hbm2java
 */
public class PhoneTab implements java.io.Serializable {

	private PhoneTabId id;
	private Events events;
	private Integer phone;

	public PhoneTab() {
	}

	public PhoneTab(PhoneTabId id, Events events) {
		this.id = id;
		this.events = events;
	}

	public PhoneTab(PhoneTabId id, Events events, Integer phone) {
		this.id = id;
		this.events = events;
		this.phone = phone;
	}

	public PhoneTabId getId() {
		return this.id;
	}

	public void setId(PhoneTabId id) {
		this.id = id;
	}

	public Events getEvents() {
		return this.events;
	}

	public void setEvents(Events events) {
		this.events = events;
	}

	public Integer getPhone() {
		return this.phone;
	}

	public void setPhone(Integer phone) {
		this.phone = phone;
	}

}
