package com.hand.pojo;

// Generated 2015-8-20 23:30:34 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Store generated by hbm2java
 */
public class Store implements java.io.Serializable {

	private Byte storeId;
	private Address address;
	private Staff staff;
	private Customer customer;
	private Date lastUpdate;
	private Set staffs = new HashSet(0);
	private Set inventories = new HashSet(0);
	private Set customers = new HashSet(0);

	public Store() {
	}

	public Store(Address address, Staff staff, Customer customer,
			Date lastUpdate) {
		this.address = address;
		this.staff = staff;
		this.customer = customer;
		this.lastUpdate = lastUpdate;
	}

	public Store(Address address, Staff staff, Customer customer,
			Date lastUpdate, Set staffs, Set inventories, Set customers) {
		this.address = address;
		this.staff = staff;
		this.customer = customer;
		this.lastUpdate = lastUpdate;
		this.staffs = staffs;
		this.inventories = inventories;
		this.customers = customers;
	}

	public Byte getStoreId() {
		return this.storeId;
	}

	public void setStoreId(Byte storeId) {
		this.storeId = storeId;
	}

	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public Set getStaffs() {
		return this.staffs;
	}

	public void setStaffs(Set staffs) {
		this.staffs = staffs;
	}

	public Set getInventories() {
		return this.inventories;
	}

	public void setInventories(Set inventories) {
		this.inventories = inventories;
	}

	public Set getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set customers) {
		this.customers = customers;
	}

}
